version: '3'

services:
  myapp1:
    restart: always
    container_name: myapp1
    build: ./APICONTAINER
    environment: 
      - APPID=1111
    ports:
      - "1111:1111"
    network_mode: host

  myapp2:
    restart: always
    container_name: myapp2
    build: ./APICONTAINER
    environment:
      - APPID=2222
    ports:
      - "2222:2222"
    network_mode: host

  myproxy:
    container_name: myproxy
    build: ./NGINXCONTAINER
    ports: 
      - "127.0.0.1:8000:8000"
    depends_on: 
      - myapp1
      - myapp2
    network_mode: host
